#!/usr/bin/env python3
"""Generates the SDF for one AprilTag model per path-planner grid intersection,
face-up on the floor, and writes it directly into worlds/warehouse.sdf between
auto-generated markers. Also generates any missing tag36h11-*.png textures.

Grid defaults mirror warehouse_control/src/path_planner.cpp's declared
parameters (grid_width, grid_height, resolution, origin_x, origin_y), so tags
land exactly on the grid lines the robot plans along.

Run this once before first launch (or any time the grid parameters change):
    ./generate_apriltag_grid.py
"""

import argparse
from pathlib import Path

MODEL_NAME = 'apriltag'
TEXTURE_DIR = Path(__file__).resolve().parent.parent / 'models' / MODEL_NAME / 'materials' / 'textures'
DEFAULT_WORLD = Path(__file__).resolve().parent.parent / 'worlds' / 'warehouse.sdf'

BEGIN_MARKER = '    <!-- BEGIN AUTO-GENERATED APRILTAG GRID: generated by generate_apriltag_grid.py, do not edit by hand -->'
END_MARKER = '    <!-- END AUTO-GENERATED APRILTAG GRID -->'

MODEL_TEMPLATE = """    <model name="floor_tag_{tag_id}">
      <static>true</static>
      <pose>{x:.4f} {y:.4f} {z:.4f} 0 0 {yaw}</pose>
      <link name="link">
        <visual name="visual">
          <geometry>
            <box>
              <size>{size} {size} {thickness}</size>
            </box>
          </geometry>
          <material>
            <ambient>1 1 1 1</ambient>
            <diffuse>1 1 1 1</diffuse>
            <specular>0 0 0 1</specular>
            <pbr>
              <metal>
                <albedo_map>model://{model_name}/materials/textures/tag36h11-{tag_id}.png</albedo_map>
              </metal>
            </pbr>
          </material>
        </visual>{collision}
      </link>
    </model>"""

COLLISION_TEMPLATE = """
        <collision name="collision">
          <geometry>
            <box>
              <size>{size} {size} {thickness}</size>
            </box>
          </geometry>
        </collision>"""


def build_snippet(args):
    expected = args.grid_width * args.grid_height
    if args.tag_count != expected:
        raise ValueError(
            f'grid is {args.grid_width}x{args.grid_height} ({expected} cells) '
            f'but tag_count is {args.tag_count} — pass matching --grid-width/--grid-height/--tag-count'
        )

    ensure_textures(args.tag_count, TEXTURE_DIR, args.texture_size, generate=not args.no_generate_textures)

    z = args.thickness / 2 + args.z_lift
    collision = COLLISION_TEMPLATE.format(size=args.size, thickness=args.thickness) if not args.no_collision else ''

    blocks = []
    for row in range(args.grid_height):
        for col in range(args.grid_width):
            tag_id = row * args.grid_width + col
            x = args.origin_x + col * args.resolution
            y = args.origin_y - row * args.resolution
            blocks.append(MODEL_TEMPLATE.format(
                tag_id=tag_id,
                x=x, y=y, z=z,
                yaw=args.yaw,
                size=args.size,
                thickness=args.thickness,
                collision=collision,
                model_name=MODEL_NAME,
            ))

    header = f'    <!-- {args.tag_count} floor AprilTags on the {args.grid_width}x{args.grid_height} path-planner grid -->'
    return '\n'.join([header] + blocks)


def ensure_textures(tag_count, texture_dir, size, generate):
    missing = [i for i in range(tag_count) if not (texture_dir / f'tag36h11-{i}.png').exists()]
    if not missing:
        return

    if not generate:
        raise FileNotFoundError(f'missing texture files in {texture_dir}: {missing}')

    try:
        import cv2
        import numpy as np
        from cv2 import aruco
    except ImportError as e:
        raise ImportError(
            'generating AprilTag textures requires OpenCV — run `pip install opencv-python` '
            'or pass --no-generate-textures and supply the PNGs yourself'
        ) from e

    texture_dir.mkdir(parents=True, exist_ok=True)
    tag_dict = aruco.getPredefinedDictionary(aruco.DICT_APRILTAG_36h11)

    # tag36h11 is 8x8 modules (6 data + 1 border ring each side); add a 1-module
    # white quiet zone on every edge to match the conventional apriltag-imgs layout.
    core_size = round(size * 8 / 10)
    offset = (size - core_size) // 2

    for tag_id in missing:
        marker = aruco.generateImageMarker(tag_dict, tag_id, core_size)
        canvas = np.full((size, size), 255, dtype=np.uint8)
        canvas[offset:offset + core_size, offset:offset + core_size] = marker
        cv2.imwrite(str(texture_dir / f'tag36h11-{tag_id}.png'), canvas)

    print(f'Generated {len(missing)} tag texture(s) in {texture_dir}')


def write_into_world(world_path, snippet):
    text = world_path.read_text()
    has_begin = BEGIN_MARKER in text
    has_end = END_MARKER in text
    if has_begin != has_end:
        raise ValueError(
            f'{world_path} has a mismatched AUTO-GENERATED APRILTAG GRID marker — '
            'fix or remove it by hand before re-running'
        )

    block = f'{BEGIN_MARKER}\n{snippet}\n{END_MARKER}'
    if has_begin:
        start = text.index(BEGIN_MARKER)
        end = text.index(END_MARKER) + len(END_MARKER)
        text = text[:start] + block + text[end:]
    else:
        close_tag = '</world>'
        idx = text.rindex(close_tag)
        text = text[:idx] + block + '\n' + text[idx:]

    world_path.write_text(text)


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--grid-width', type=int, default=8)
    parser.add_argument('--grid-height', type=int, default=9)
    parser.add_argument('--resolution', type=float, default=1.0)
    parser.add_argument('--origin-x', type=float, default=-3.0)
    parser.add_argument('--origin-y', type=float, default=4.0)
    parser.add_argument('--tag-count', type=int, default=72, help='number of tags to place/generate (must equal grid_width * grid_height)')
    parser.add_argument('--size', type=float, default=0.05, help='tag edge length in meters (incl. white margin)')
    parser.add_argument('--thickness', type=float, default=0.001, help='decal thickness in meters')
    parser.add_argument('--z-lift', type=float, default=0.0001, help='extra clearance above the ground plane to avoid z-fighting')
    parser.add_argument('--yaw', type=float, default=0.0, help='fixed yaw (radians) applied to every tag')
    parser.add_argument('--no-collision', action='store_true', help='omit collision geometry for the tags')
    parser.add_argument('--world', type=Path, default=DEFAULT_WORLD, help='SDF world file to update in place (ignored if --output is given)')
    parser.add_argument('--output', type=Path, default=None, help='write a standalone XML snippet here instead of editing --world in place')
    parser.add_argument('--no-generate-textures', action='store_true', help='fail on missing tag textures instead of generating them with OpenCV')
    parser.add_argument('--texture-size', type=int, default=650, help='pixel width/height for generated tag textures')
    return parser.parse_args()


def main():
    args = parse_args()
    snippet = build_snippet(args)
    if args.output:
        args.output.write_text(snippet + '\n')
        print(f'Wrote {args.grid_width * args.grid_height} tag models to {args.output}')
    else:
        write_into_world(args.world, snippet)
        print(f'Wrote {args.grid_width * args.grid_height} tag models into {args.world}')


if __name__ == '__main__':
    main()
