controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    flap_controller:
      type: position_controllers/JointGroupPositionController

flap_controller:
  ros__parameters:
    joints:
      - front_flap_joint
    use_sim_time: true

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    # Distance between the two driven wheel centers and their rolling radius (m)
    wheel_separation: 0.81
    wheel_radius: 0.1

    base_frame_id: base_footprint
    odom_frame_id: odom
    publish_rate: 50.0

    pose_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    open_loop: false
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    use_sim_time: true
